#!/usr/bin/env python3

"""Regenerate the Python-compatible subsets of ok.lst and nok.lst.

Run as `make pysubset`.

tests/ok.lst and tests/nok.lst are written in the Emacs dialect this
engine implements: "\\(" groups, "\\|" alternates, "\\{2\\}" repeats, and
"[[:blank:]]" is a class name. Python's `re` reads all of those as
literals, so a row like "foo\\|bar" tests nothing when the subjects come
from Python. Those rows belong to tests/test1.c, which executes every row
of both files.

What is left is the subset both dialects agree on, and that agreement is
measured here rather than guessed: an ok row survives when Python's
leftmost match has exactly the length ok.lst records, and a nok row
survives when Python finds no match at all -- the same two questions
tests/test_rand and tests/test_rand_neg ask the C engine.
"""

import re
import sys
import warnings

# "[[:blank:]]" is a class name here and a nested set to Python; the row is
# about to be rejected for exactly that reason, so its warning is noise.
warnings.simplefilter("ignore", FutureWarning)

ROW = re.compile(r'^(?P<pattern>[^\t]+)\t+"(?P<text>.*)"\s*(?P<length>\d+)?\s*$')

HEADER = """\
# GENERATED by scripts/select_python_subset.py -- run `make pysubset`.
#
# The rows of tests/{source} whose meaning is the same in Python's `re` as
# in the Emacs dialect this engine implements, and only those: the drivers
# in scripts/ generate their subjects with Python, so a row Python reads
# differently would test the wrong language. Every row of tests/{source}
# is executed by tests/test1.c regardless.
#
# {kept} of {total} rows.
"""


def unquote(text):
	return (text.replace("\\n", "\n").replace("\\t", "\t")
		.replace("\\r", "\r"))


def rows(path):
	with open(path, "rt", encoding="utf-8") as handle:
		for line in handle:
			if not line.strip() or line.startswith("#"):
				continue
			match = ROW.match(line.rstrip("\n"))
			if match is None:
				continue
			yield (match.group("pattern"), match.group("text"),
			       int(match.group("length") or 0), line.rstrip("\n"))


# Constructs the two dialects spell the same and read differently. The
# behavioural check below only asks about the one subject the row records,
# and that is not enough: Python reads "[[:word:]]" as the set of the
# characters ":dorw", which happens to agree with the class on "_" and
# disagrees on every letter, so the row passed the check and then failed
# against thousands of generated subjects.  The subject anchors are the
# same trap: Python reads "abc\\'" as the four characters "abc'", which
# finds no match in "abcd" for a reason that has nothing to do with the
# end of the subject, so the row would be selected and then fail on the
# first generated subject ending in "abc".
DIALECT = ("\\(", "\\)", "\\|", "\\{", "\\}", "[[:", "{", "}", "\\x",
	   "\\`", "\\'")


def compatible(pattern, text, length, positive):
	if any(token in pattern for token in DIALECT):
		return False
	try:
		found = re.search(unquote(pattern), unquote(text))
	except re.error:
		return False
	if positive:
		return found is not None and len(found.group(0)) == length
	return found is None


def select(source, dest, positive):
	kept = []
	total = 0
	for pattern, text, length, raw in rows(source):
		total += 1
		if compatible(pattern, text, length, positive):
			kept.append(raw)
	with open(dest, "w", encoding="utf-8") as handle:
		handle.write(HEADER.format(source=source.split("/")[-1],
					   kept=len(kept), total=total))
		for raw in kept:
			handle.write(raw + "\n")
	print(f"{dest}: {len(kept)} of {total} rows from {source}")


def main():
	select("tests/ok.lst", "tests/pyok.lst", True)
	select("tests/nok.lst", "tests/pynok.lst", False)
	return 0


if __name__ == "__main__":
	sys.exit(main())
